name: ieeewie
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  #ui
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  flutter_screenutil: ^5.7.0
  animate_do: ^3.0.2
  flutter_rating_bar: ^4.0.1
  overlay_support: ^2.0.1
  fluttertoast: ^8.0.8
  expandable: ^5.0.1
  flutter_native_splash: ^2.1.5
  flutter_svg: ^2.0.2
  animations: ^2.0.7
  timeline_tile: ^2.0.0
  flutter_expanded_tile: ^0.3.7
  loader_overlay: ^2.2.0


  # Routing
  auto_route: ^5.0.2

  #firebase
  firebase_auth_mocks: ^0.11.0
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  firebase_storage: ^11.0.6
  cloud_firestore: ^4.4.5
  google_sign_in: ^6.0.2
  firebase_ui_firestore: ^1.3.2
  firebase_messaging: ^14.2.5
  firebase_analytics: ^10.0.7

  #utility
  path_provider: ^2.0.14
  image_picker: ^0.8.7
  file_picker: ^5.2.6
  rxdart: ^0.27.3
  fpdart: ^0.4.0
  connectivity_plus: ^3.0.2
  flutter_local_notifications: ^13.0.0
  equatable: ^2.0.5
  google_fonts: ^4.0.3
  url_launcher: ^6.1.10
  appinio_video_player: ^1.2.0

  #state management
  flutter_riverpod: 2.3.2
  event_bus: ^2.0.0

  # Local Storage
  shared_preferences: any
  hive: ^2.2.3
  hive_flutter: ^1.1.0


  # App Updates
  in_app_update: ^4.0.1
  upgrader: ^5.0.0
  in_app_review: any
  uuid: ^3.0.5

  # Debugging and Testing
  logging: ^1.0.2
  mockito: ^5.3.2
  lint: any

dev_dependencies:
  hive_generator: ^2.0.0
  auto_route_generator: ^5.0.3
  flutter_native_splash: ^2.2.17
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf

flutter_native_splash:
  color: "090619"

flutter_rename_app_plus:
  application_name: IEEE WIE
  dart_package_name: IEEE WIE
  application_id: com.r8_ieee.www
  bundle_id: com.r8_ieee.www
  android_package_name: com.r8_ieee.www

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ieeelogo.png"
  remove_alpha_ios: true