// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvBblFXV1q-H9_CG-8qiIg3Yb3LFpuZaY',
    appId: '1:28405878938:web:a572a2c029ee764cdd4f23',
    messagingSenderId: '28405878938',
    projectId: 'ieeewie-cd8d5',
    authDomain: 'ieeewie-cd8d5.firebaseapp.com',
    storageBucket: 'ieeewie-cd8d5.appspot.com',
    measurementId: 'G-9KXZ2BHDQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHsWPXV6UDyJ4q3NXMdwjXijKGTKH7Vck',
    appId: '1:28405878938:android:e19e326c303423dbdd4f23',
    messagingSenderId: '28405878938',
    projectId: 'ieeewie-cd8d5',
    storageBucket: 'ieeewie-cd8d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdOQXZvcTkNRCq_O3fOs76EfCTOx0oGBs',
    appId: '1:28405878938:ios:7323363581d308e0dd4f23',
    messagingSenderId: '28405878938',
    projectId: 'ieeewie-cd8d5',
    storageBucket: 'ieeewie-cd8d5.appspot.com',
    iosClientId: '28405878938-m51rku0o5h5ll0ku3ss5amett732ihqf.apps.googleusercontent.com',
    iosBundleId: 'com.ieeewie.ieeewie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdOQXZvcTkNRCq_O3fOs76EfCTOx0oGBs',
    appId: '1:28405878938:ios:7323363581d308e0dd4f23',
    messagingSenderId: '28405878938',
    projectId: 'ieeewie-cd8d5',
    storageBucket: 'ieeewie-cd8d5.appspot.com',
    iosClientId: '28405878938-m51rku0o5h5ll0ku3ss5amett732ihqf.apps.googleusercontent.com',
    iosBundleId: 'com.ieeewie.ieeewie',
  );
}
